from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
import datetime

class EnterpriseDataModel38_0(BaseModel):
    '''Auto-generated massive data model 38_0'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_1(BaseModel):
    '''Auto-generated massive data model 38_1'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_2(BaseModel):
    '''Auto-generated massive data model 38_2'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_3(BaseModel):
    '''Auto-generated massive data model 38_3'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_4(BaseModel):
    '''Auto-generated massive data model 38_4'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_5(BaseModel):
    '''Auto-generated massive data model 38_5'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_6(BaseModel):
    '''Auto-generated massive data model 38_6'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_7(BaseModel):
    '''Auto-generated massive data model 38_7'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_8(BaseModel):
    '''Auto-generated massive data model 38_8'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_9(BaseModel):
    '''Auto-generated massive data model 38_9'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_10(BaseModel):
    '''Auto-generated massive data model 38_10'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_11(BaseModel):
    '''Auto-generated massive data model 38_11'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_12(BaseModel):
    '''Auto-generated massive data model 38_12'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_13(BaseModel):
    '''Auto-generated massive data model 38_13'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_14(BaseModel):
    '''Auto-generated massive data model 38_14'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_15(BaseModel):
    '''Auto-generated massive data model 38_15'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_16(BaseModel):
    '''Auto-generated massive data model 38_16'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_17(BaseModel):
    '''Auto-generated massive data model 38_17'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_18(BaseModel):
    '''Auto-generated massive data model 38_18'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel38_19(BaseModel):
    '''Auto-generated massive data model 38_19'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

