from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
import datetime

class EnterpriseDataModel14_0(BaseModel):
    '''Auto-generated massive data model 14_0'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_1(BaseModel):
    '''Auto-generated massive data model 14_1'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_2(BaseModel):
    '''Auto-generated massive data model 14_2'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_3(BaseModel):
    '''Auto-generated massive data model 14_3'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_4(BaseModel):
    '''Auto-generated massive data model 14_4'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_5(BaseModel):
    '''Auto-generated massive data model 14_5'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_6(BaseModel):
    '''Auto-generated massive data model 14_6'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_7(BaseModel):
    '''Auto-generated massive data model 14_7'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_8(BaseModel):
    '''Auto-generated massive data model 14_8'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_9(BaseModel):
    '''Auto-generated massive data model 14_9'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_10(BaseModel):
    '''Auto-generated massive data model 14_10'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_11(BaseModel):
    '''Auto-generated massive data model 14_11'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_12(BaseModel):
    '''Auto-generated massive data model 14_12'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_13(BaseModel):
    '''Auto-generated massive data model 14_13'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_14(BaseModel):
    '''Auto-generated massive data model 14_14'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_15(BaseModel):
    '''Auto-generated massive data model 14_15'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_16(BaseModel):
    '''Auto-generated massive data model 14_16'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_17(BaseModel):
    '''Auto-generated massive data model 14_17'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_18(BaseModel):
    '''Auto-generated massive data model 14_18'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel14_19(BaseModel):
    '''Auto-generated massive data model 14_19'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

