from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
import datetime

class EnterpriseDataModel25_0(BaseModel):
    '''Auto-generated massive data model 25_0'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_1(BaseModel):
    '''Auto-generated massive data model 25_1'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_2(BaseModel):
    '''Auto-generated massive data model 25_2'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_3(BaseModel):
    '''Auto-generated massive data model 25_3'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_4(BaseModel):
    '''Auto-generated massive data model 25_4'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_5(BaseModel):
    '''Auto-generated massive data model 25_5'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_6(BaseModel):
    '''Auto-generated massive data model 25_6'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_7(BaseModel):
    '''Auto-generated massive data model 25_7'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_8(BaseModel):
    '''Auto-generated massive data model 25_8'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_9(BaseModel):
    '''Auto-generated massive data model 25_9'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_10(BaseModel):
    '''Auto-generated massive data model 25_10'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_11(BaseModel):
    '''Auto-generated massive data model 25_11'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_12(BaseModel):
    '''Auto-generated massive data model 25_12'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_13(BaseModel):
    '''Auto-generated massive data model 25_13'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_14(BaseModel):
    '''Auto-generated massive data model 25_14'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_15(BaseModel):
    '''Auto-generated massive data model 25_15'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_16(BaseModel):
    '''Auto-generated massive data model 25_16'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_17(BaseModel):
    '''Auto-generated massive data model 25_17'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_18(BaseModel):
    '''Auto-generated massive data model 25_18'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

class EnterpriseDataModel25_19(BaseModel):
    '''Auto-generated massive data model 25_19'''
    field_str_0: str = Field(default='enterprise_0')
    field_int_0: int = Field(default=0)
    field_dict_0: Dict[str, Any] = Field(default_factory=dict)
    field_str_1: str = Field(default='enterprise_1')
    field_int_1: int = Field(default=1)
    field_dict_1: Dict[str, Any] = Field(default_factory=dict)
    field_str_2: str = Field(default='enterprise_2')
    field_int_2: int = Field(default=2)
    field_dict_2: Dict[str, Any] = Field(default_factory=dict)
    field_str_3: str = Field(default='enterprise_3')
    field_int_3: int = Field(default=3)
    field_dict_3: Dict[str, Any] = Field(default_factory=dict)
    field_str_4: str = Field(default='enterprise_4')
    field_int_4: int = Field(default=4)
    field_dict_4: Dict[str, Any] = Field(default_factory=dict)
    field_str_5: str = Field(default='enterprise_5')
    field_int_5: int = Field(default=5)
    field_dict_5: Dict[str, Any] = Field(default_factory=dict)
    field_str_6: str = Field(default='enterprise_6')
    field_int_6: int = Field(default=6)
    field_dict_6: Dict[str, Any] = Field(default_factory=dict)
    field_str_7: str = Field(default='enterprise_7')
    field_int_7: int = Field(default=7)
    field_dict_7: Dict[str, Any] = Field(default_factory=dict)
    field_str_8: str = Field(default='enterprise_8')
    field_int_8: int = Field(default=8)
    field_dict_8: Dict[str, Any] = Field(default_factory=dict)
    field_str_9: str = Field(default='enterprise_9')
    field_int_9: int = Field(default=9)
    field_dict_9: Dict[str, Any] = Field(default_factory=dict)

